name = "staging_sms_bot"
compatibility_date = "2024-10-28"
compatibility_flags = ["nodejs_compat"]
main = "src/index.ts"
[observability]
enabled = true
[vars]
DATABASE_URL = "$DATABASE_URL"
TELEGRAM_API_SECRET_URL = "$TELEGRAM_API_SECRET_URL"